name: joy2twist
adopt-info: joy2twist
license: Apache-2.0
summary: Convert joy commands to twist
description: |
  Convert joy commands to twist

grade: devel
confinement: devmode
base: core22

architectures:
  - build-on: arm64

# Later to be parsed from git repo
version: "0.0.1"

apps:
  joy2twist:
    command: usr/bin/launcher.sh
    plugs: [network, network-bind, joystick]
    daemon: simple
    install-mode: disable
    extensions: [ros2-humble]

parts:
  joy2twist:
    plugin: colcon
    source: https://github.com/husarion/joy2twist.git
    source-branch: ros2
    build-packages:
      - ros-humble-ament-lint-auto
    stage-packages:
      - ros-humble-ros2launch
      - ros-humble-rmw-cyclonedds-cpp

  # copy local scripts to the snap usr/bin
  local-files:
    plugin: dump
    source: snap/local/
    organize:
      "*.sh": usr/bin/
